### ISSUE TITLE
[BUG] Microfilm doesn't install?

### ISSUE THREAD

**Issue by mat10d** [cheeseman-lab/brieflow#30]
Having issues installing microfilm. @pupusam--please add more specifics on this issue here. Should work once Bryce accepts the git request.

**Comment by pupasam** [comment]
<img width="671" alt="Screenshot 2024-12-15 at 6 14 03 PM" src="https://github.com/user-attachments/assets/03834cca-a640-4ba0-aa47-c432b9375377" />
<img width="748" alt="Screenshot 2024-12-15 at 6 14 41 PM" src="https://github.com/user-attachments/assets/a3f9d2bd-6f9d-42bb-ac0a-cbdde949f991" />

**Comment by pupasam** [comment]
Running the default install .yml did not seem to install microfilm. The ModuleNotFound error occurs inside the brieflow conda environment. I cannot manually install the module with conda --- that is the error 'warning libmamba'.

**Comment by pupasam** [comment]
It looks like this is a more holistic error -- also getting install errors with matplotlib and nd2, maybe more.
<img width="795" alt="Screenshot 2024-12-16 at 9 17 08 AM" src="https://github.com/user-attachments/assets/f4352d51-0081-4f60-a7c9-1fde24d585bc" />
<img width="743" alt="Screenshot 2024-12-16 at 9 18 20 AM" src="https://github.com/user-attachments/assets/c38d3258-c253-4aab-a79c-d7bbe0f20a03" />

**Comment by pupasam** [comment]
I used the standard conda env create --file=brieflow_workflows_env.yml to make my environment, which successfully activates with conda activate brieflow_workflows.

**Comment by mat10d** [comment]
Okay, and in using `conda env create --file=brieflow_workflows_env.yml`, you got no error output? Because that's what would be more helpful in trying to figure out what is going wrong.

**Comment by roshankern** [comment]
@pupasam Are you using the `brieflow_workflows` environment for the configuration notebooks? The `brieflow_configuration` should be used for these notebooks. You can generate this environment with the file at `brieflow_configuration_env.yml`

**Comment by roshankern** [comment]
Follow these steps to install: 
https://github.com/cheeseman-lab/brieflow?tab=readme-ov-file#set-up-brieflow-configuration-environment

**Comment by pupasam** [comment]
Yes I'm using the workflows environment and had no install errors. I got around this issue by setting the channel priority to flexible instead of strict and then installing what I needed.

**Comment by pupasam** [comment]
Ok think we solved the problem -- my mistake at not realizing there were two separate environments! Thank you!!
