### ISSUE TITLE
Allocate HPC Resources

### ISSUE THREAD

**Issue by roshankern** [cheeseman-lab/brieflow#7]
For now all of the Brieflow testing has been done locally. Long term, we need to consider how Brieflow can most easily be run on Slurm/other clusters.

**Comment by roshankern** [comment]
Sunbeam instructions for running on Slurm Clusters:

https://sunbeam.readthedocs.io/en/stable/examples.html#running-on-a-slurm-cluster

**Comment by mat10d** [comment]
Ok, based on the sunbeam instructions, we will have it fully run on slurm. You can either launch from a bash script, and spawn slurm jobs for all the individual jobs, or launch from a slurm script and spawn as previously. I think we should have a fully slurm version per the sunbeam instructions--will aim for that in a coming PR.

**Comment by mat10d** [comment]
Done in #18. We will have to continue creating analogous slurm compatible files as we migrate more code. If I may suggest a path forward, I would suggest that as you make bash scripts for individual rules, make an analogous hpc script for those rules. I will test them and update the slurm/config.yaml file alongside you once you do this.
